### ISSUE TITLE
Use in FPComplete IDE

### ISSUE THREAD

**Issue by MonrealRyan** [nikita-volkov/hasql-postgres#13]
Hi, 
I'm new to haskell, i would like to ask a little but of code or instruction on how to implement this on FPComplete IDE?

**Comment by nikita-volkov** [comment]
I'm not sure what you're asking here.

**Comment by MonrealRyan** [comment]
[FPComplete](fpcomplete.com) provide an online IDE for haskell programmer.. and that's also what i'm using right now. you'r package was use to connect in Postgersql Database and also my preference on my current project. i would like to import you package in that IDE..

Hope you can help me...

**Comment by nikita-volkov** [comment]
You should consult the IDE docs on using libraries.
