### ISSUE TITLE
Hashing LocalKey does not use Oids?

### ISSUE THREAD

**Issue by arkhamist** [nikita-volkov/hasql-postgres#14]
This is a question regarding the internals of this library. 

In `Execution.hs`, when hashing `LocalKey`, the `types` part of the key is ignored. Is a prepared statement not dependent on the types of the arguments that are templated?

```haskell
instance Hashable LocalKey where
  hashWithSalt salt (LocalKey template types) =
    hashWithSalt salt template
```

For example, when I execute the following statements in psql : 

    > create table t1 (id SERIAL, c1 timestamptz);
    > prepare p1 (timestamptz) AS select * from t1 where c1 = $1;
    > drop table t1;
    > create table t1 (id SERIAL, c1 integer);
    > execute p1(1);
    ERROR:  parameter $1 of type integer cannot be coerced to the expected type timestamp with time zone
    HINT:  You will need to rewrite or cast the expression.

But, the same things works with hasql : 
```haskell
ct <- liftIO $ getCurrentTime 
l1 <- H.tx Nothing $ do
    H.unitEx [H.stmt|DROP TABLE IF EXISTS t1|]
    H.unitEx [H.stmt|CREATE TABLE t1 (id SERIAL, c1 timestamptz)|]
    H.listEx $ [H.stmt|SELECT (id, c1) FROM t1 WHERE c1 = ?|] ct
forM_ l1 $ \(id :: Int, c1 :: UTCTime) -> do
    liftIO $ putStrLn $ "id: " ++ show id ++ ", c1: " ++ show c1

l2 <- H.tx Nothing $ do
    H.unitEx [H.stmt|DROP TABLE t1|]
    H.unitEx [H.stmt|CREATE TABLE t1 (id SERIAL, c1 integer)|]
    H.listEx $ [H.stmt|SELECT (id, c1) FROM t1 WHERE c1 = ?|] (1 :: Int)
forM_ l2 $ \(id :: Int, c1 :: Int) -> do
    liftIO $ putStrLn $ "id: " ++ show id ++ ", c1: " ++ show c1

```

When the 2nd select statement is executed (in hasql), a prepared statement for it will be present in the hashtable (as only the template is used as a key when inserting into the hashtable, not a combination of template and the types of the arguments), so, the same prepared statement (created from the first select statement) is executed with a value of different type. How is it that there is no error with hasql in this case?

**Comment by nikita-volkov** [comment]
> only the template is used as a key when inserting into the hashtable, not a combination of template and the types of the arguments

You're mistaken. I suspect, [the `Hashable` instance](https://github.com/nikita-volkov/hasql-postgres/blob/master/library/Hasql/Postgres/Session/Execution.hs#L27-L29) confused you. It only affects how the hash-table performs, allowing for faster hashing at a price of an inevitable hash collision in such cases as yours, which are naturally rare. Hash collision however is an event, which is anticipated by any hash-table implementation, and gets resolved by downgrading to the equality comparison of keys - that's when the keys get discerned using both the template and the types.

**Comment by arkhamist** [comment]
That instance declaration threw me off. Anyway, the `Env` declaration makes it clear that `LocalKey` is actually the key: 
```haskell
type Env = (PQ.Connection, IORef Word16, Hashtables.BasicHashTable LocalKey RemoteKey)
```
I've one more question regarding `LocalKey`. As I understand, you store the template which is not  converted (as written in the `Stmt` quasiquoter) in `LocalKey`. Is there any specific reason for doing this? Wouldn't it also be right to store the converted statement?

**Comment by nikita-volkov** [comment]
> As I understand, you store the template which is not converted (as written in the Stmt quasiquoter) in LocalKey. Is there any specific reason for doing this? Wouldn't it also be right to store the converted template?

Using a converted template in the key would require to make the conversion before each access to the key, while in the current implementation the conversion gets only done once.

**Comment by arkhamist** [comment]
Okay. That makes perfect sense.
