### ISSUE TITLE
Postgres version limitation

### ISSUE THREAD

**Issue by denismo** [nikita-volkov/hasql-postgres#18]
Hi Nikita,

we wanted to use Postgrest, which depends on your library, to expose our AWS Redshift database via HTTP interface. Unfortunately, when Postgrest makes a query, it reports the following error: ```Postgres version 8...2 is not supported```

I tracked it down and narrowed it down to the code in your library, because it is returned as UnsupportedVersion error from your library. The redshift database returns the following version info:```PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.958 ```

1. I'm a bit puzzled because in your code I see that you check v < 80200 so the check should pass?

2. But also, if we are only going to query the database (only SELECT), will this version limitation be critical? Or saying it differently, do you know which features of older version are you relying on? If we ignore this limitation (by creating a custom build of your library) might it still work with PostgreSQL 8.0.2 (at least for SELECTs) or are there major interface differences which will make it unusable?

Thanks.

Denis

**Comment by nikita-volkov** [comment]
Hi Denis,

1. According to Postgres' format, 80200 maps to 8.2.0.

2. Making a custom build of the library should generally solve your issue. The failures will be possible when dealing with intervals or other date formats as far as I recall. Either way, you'll be able to easily check the supported features by running the test suite.

**Comment by denismo** [comment]
Hi Nikita,
thanks for prompt reply and explanation.
Denis
