### ISSUE TITLE
A small example on how to use Unknown Type

### ISSUE THREAD

**Issue by ruslantalpa** [nikita-volkov/hasql-postgres#23]
I am trying to contribute to PostgREST which uses hasql-postgres to talk to the db

I am having a bit of trouble turning this
```
... <- H.listEx [H.stmt|SELECT * FROM projects WHERE id = '1'::unknown|]
```
into
```
... <- H.listEx [H.stmt|SELECT * FROM projects WHERE id =  ?|] (HP.Unknown "1")
```
i get
```
Left (TxError (ErroneousResult "08P01" "insufficient data left in message" Nothing Nothing))
```

I am trying to send data that come from untrusted sources as parameters for a prepared statement and let postgresql do the casting
Thank you

**Comment by ruslantalpa** [comment]
Here is a minimal example, what am i doing wrong?
http://lpaste.net/28146681627279360

**Comment by nikita-volkov** [comment]
The `Unknown` wrapper is not what you expected. [See the docs](http://hackage.haskell.org/package/hasql-postgres-0.10.6/docs/Hasql-Postgres.html#t:Unknown).

**Comment by ruslantalpa** [comment]
I see, any way of sending parameters as Text and having postgresql cast them to int/float as needed

**Comment by nikita-volkov** [comment]
@ruslantalpa Nope. However it is not a limitation of Hasql, but of Postgres' binary protocol.
