### ISSUE TITLE
Question on values returned that are of type json

### ISSUE THREAD

**Issue by ruslantalpa** [nikita-volkov/hasql-postgres#25]
So this code works as expected
```
{-# LANGUAGE QuasiQuotes, ScopedTypeVariables, OverloadedStrings #-}

import Control.Monad.IO.Class
import Data.Foldable
import Data.Text
import qualified Hasql as H
import qualified Hasql.Postgres as HP
import qualified Data.Aeson as J
import           Data.String.Conversions   (cs)

main :: IO ()
main = do

  let postgresSettings = HP.ParamSettings "localhost" 5432 "aaa" "bbb" "ccc"
  poolSettings <- maybe (fail "Improper session settings") return $
                  H.poolSettings 6 30

  pool :: H.Pool HP.Postgres
       <- H.acquirePool postgresSettings poolSettings

  H.session pool $ do
    rows <- H.tx Nothing $ H.listEx $ [H.stmt|
      SELECT 1 as int, '{"a": 10, "b": [1,2,"3"], "c": {"d":1, "e": false}}'::json as value
    |]
    forM_ rows $ \(int :: Int, value :: J.Value) ->
      liftIO $ putStrLn $ "ID: " ++ show int ++ ", Value: " ++ show value

  H.releasePool pool

```
the output is

```
ID: 1, Value: Object (fromList [("a",Number 10.0),("b",Array [Number 1.0,Number 2.0,String "3"]),("c",Object (fromList [("d",Number 1.0),("e",Bool False)]))])
```

I would like to understand the cost of this operation, i.e. how the PostgreSQL binary protocol is sending over this value, is it basically a string or is it some type of AST that represents the json.
Looking at this line [L273](https://github.com/nikita-volkov/hasql-postgres/blob/master/library/Hasql/Postgres/Mapping.hs#L273) it seems the data is coming back as a string. Is this right?

If it's coming back as a string, then am i right to assume that if the type for value was specified as "value :: Text" then basically what would have happen is an decode then encode?

Thank you

**Comment by nikita-volkov** [comment]
> it seems the data is coming back as a string. Is this right?

Right. An ASCII-encoded string.

> If it's coming back as a string, then am i right to assume that if the type for value was specified as "value :: Text" then basically what would have happen is an decode then encode?

I don't know :) Try it!

**Comment by ruslantalpa** [comment]
Well, i know it works, i tried it and the result is as expected
```
ID: 1, Value: "{\"a\": 10, \"b\": [1,2,\"3\"], \"c\": {\"d\":1, \"e\": false}}"
```
 I am just not smart enough to figure out where the "J.encode" is happening :)
My concern with it is that if someone (PostgREST) is expecting a json value and it needs it's string representation (to pass it on) then somehow along the chain (hasql/aeson) a wasteful decode/encode is happening and i was wandering if somehow this could be avoided, i.e. set the type to something else then ::Text in order to have hasql pass the raw ASCI string and use that.

**Comment by ruslantalpa** [comment]
Oh, i think i get it, if i set the type to ::Text then this part of the code is used
https://github.com/nikita-volkov/hasql-postgres/blob/master/library/Hasql/Postgres/Mapping.hs#L234
which means i get the string i desire :)
Sorry

**Comment by nikita-volkov** [comment]
You got that part right. However I'd recommend going with ::ByteString, whose decoder simply passes the bytes as they are, while the decoder of ::Text applies a UTF8-decoding, which might be redundant in your case.
