### ISSUE TITLE
High memory consumption when trying to run large INSERT query

### ISSUE THREAD

**Issue by ruslantalpa** [nikita-volkov/hasql-postgres#28]
When profiling postgrest with +RTS -hd and trying to send a 6M json (which would roughly translate the the same size of the insert query) the top data constructors that consume the memory are from Hasql

```
<Hasql.Postgres.Statement.TemplateConverter.Parser.sat_s14KF>
<Hasql.Postgres.Statement.TemplateConverter.Parser.succ_s14Ks> 
<Hasql.Postgres.Statement.TemplateConverter.Parser.sat_s14Jj>
<Hasql.Postgres.Statement.TemplateConverter.Parser.sat_s14BQ>
<Hasql.Postgres.Statement.TemplateConverter.Parser.a11_s14yf>
```

The context is here https://github.com/begriffs/postgrest/issues/360#issuecomment-157740559

The output of the profiling looks like this
![postgrest](https://cloud.githubusercontent.com/assets/5537246/11244559/cf17bf28-8e16-11e5-9ec8-6494ab9fdc73.png)

We create the statement here https://github.com/begriffs/postgrest/blob/master/src/PostgREST/App.hs#L430
which is basically a 

```
B.Stmt (sql::Text) empty True
```

and it's executed here
https://github.com/begriffs/postgrest/blob/master/src/PostgREST/App.hs#L117

Are we doing something wrong, could we be doing it in another way?
Thank you

**Comment by ruslantalpa** [comment]
I see "TemplateConverter.Parser" being at the center of it, leading me to think that you are actually looking for "?" in the sql that is being supplied.
In our case, there is no such thing, there are no parameters. 
Could we be constructing the statement in some other way to go around the parser inside Hasql?

**Comment by nikita-volkov** [comment]
The new version, which is slated for release in two weeks, won't touch the query at all, which will eradicate this issue altogether.

**Comment by ruslantalpa** [comment]
Thank you, any way to avoid this issue in the current release?

**Comment by nikita-volkov** [comment]
Use the parametric query instead of rendering JSON in the SQL. Current version supports JSON values.

**Comment by begriffs** [comment]
In our case we're not inserting a single big JSON object which we could parameterize with `?`. What we're doing is transforming a json array such as

```json
[
  { "x": 1, "y":2, "z":3},
  { "x": 4, "y":5, "z":6}
]
```

Into an insert statement like this

```sql
insert into foo (x, y, z)
values (1,2,3), (4,5,6)
```

So our our sql can get very long and contains no parameter placeholders (we sanitize the inputs).

Now that I explain how we're doing things I'm wondering if we should instead be using something like the postgres `json_populate_recordset` function.

**Comment by nikita-volkov** [comment]
Alternatively you can try encoding it as array on the Haskell side and using [the `unnest` function](http://www.postgresql.org/docs/current/static/functions-array.html). E.g.:

```sql
insert into foo (x, y, z) unnest(?)
```

I don't know if it'll work, but worth a try.

**Comment by nikita-volkov** [comment]
Oops. I forgot that this version doesn't support the composite types. Nevermind.
